language: ruby

matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="--2.0"

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: short-hostname
